services:
  template-dotnet:
    build:
      context: ./sdks/dotnet
      dockerfile: template.Dockerfile
    ports:
      - '5550:5550'
    environment:
      - ASPNETCORE_URLS=http://+:5550
  template-node:
    build:
      context: ./sdks/node
      dockerfile: template.Dockerfile
    ports:
      - '5551:5550'
  template-python:
    build:
      context: ./sdks/python
      dockerfile: template.Dockerfile
    ports:
      - '5552:5550'
