version: '3'

vars:
  PLATFORM: sulfone
  SERVICE: helium

includes:
  dotnet:
    taskfile: sdks/dotnet/Taskfile.yaml
    dir: sdks/dotnet
  node:
    taskfile: sdks/node/Taskfile.yaml
    dir: sdks/node
  python:
    taskfile: sdks/python/Taskfile.yaml
    dir: sdks/python
