version: '3'

tasks:
  template:
    desc: Run the template
    cmds:
      - poetry run python template_test.py
  version:
    desc: Update package version
    cmds:
      - ./scripts/ci/update_version.sh {{.CLI_ARGS}}
  build:
    desc: Build the package
    cmds:
      - poetry build
