version: '3'

tasks:
  version:
    desc: Update package version
    cmds:
      - ./scripts/ci/update_version.sh {{.CLI_ARGS}}
  package:
    desc: Package the .NET version
    cmds:
      - ./scripts/ci/publish.sh {{.CLI_ARGS}}
  template:
    desc: Run a sample dotnet template
    dir: sulfone-helium-template-api
    env:
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: 'true'
      ASPNETCORE_URLS: http://+:5550
    cmds:
      - dotnet watch
  processor:
    desc: Run a sample dotnet processor
    dir: sulfone-helium-processor-api
    env:
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: 'true'
      ASPNETCORE_URLS: http://+:5551
    cmds:
      - dotnet watch
