version: '3'

tasks:
  setup:
    desc: Setup the project
    cmds:
      - bun install
  version:
    desc: Update package version
    cmds:
      - ./scripts/update_version.sh {{.CLI_ARGS}}
  template:
    desc: Run a test template
    cmds:
      - bun template_test.ts
