version: '3'

tasks:
  version:
    desc: Update package version
    cmds:
      - ./sdks/node/scripts/ci/update_version.sh {{.CLI_ARGS}}
  package:
    desc: Package the .NET version
    cmds:
      - ./sdks/node/scripts/ci/publish.sh {{.CLI_ARGS}}
