version: '3'

tasks:
  version:
    desc: Update package version
    cmds:
      - ./scripts/ci/update_version.sh {{.CLI_ARGS}}
  package:
    desc: Package the .NET version
    cmds:
      - ./scripts/ci/publish.sh {{.CLI_ARGS}}
  template:
    desc: Run a test template
    cmds:
      - bun template_test.ts
