name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish Packages
    uses: ./.github/workflows/⚡reusable-cd.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: helium
