name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: helium

  template-test:
    name: Template Test
    uses: ./.github/workflows/⚡reusable-tests.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: helium
      docker_compose: docker-compose.template.yaml
      k6: template-api-test.js
