name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: helium

  cyanprint-test:
    name: CyanPrint Test
    uses: ./.github/workflows/⚡reusable-cyanprint-test.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: helium
