name: CI-CD

on:
  push:

jobs:
  precommit:
    name: Pre-commit Check
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-sulfone-helium-nix-store-cache
      - nscloud-git-mirror-1gb
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v1.2.1

      # Pre Commit
      - name: Run pre-commit
        run: nix develop .#ci -c ./scripts/ci/pre-commit.sh

  publishnode:
    name: Publish NodeJS
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-sulfone-helium-publish-node-cache
      - nscloud-git-mirror-1gb
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v1.2.1
      - uses: AtomiCloud/actions.cache-npm@v1.0.1

        # Publish
      - uses: rlespinasse/github-slug-action@v5.x
        with:
          short-length: 7
      - name: Publish
        env:
          GITHUB_REPO_REF: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_BRANCH: ${{ env.GITHUB_REF_SLUG_URL }}

          RELEASE: 'false'

          NPM_API_KEY: ${{ secrets.NPM_API_KEY }}
        run: nix develop .#ci -c sdks/node/scripts/ci/publish.sh

  publishdotnet:
    name: Publish .NET
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-sulfone-helium-publish-nuget-cache
      - nscloud-git-mirror-1gb
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v1.2.1
      - uses: AtomiCloud/actions.cache-nuget@v1.0.1

        # Publish
      - uses: rlespinasse/github-slug-action@v5.x
        with:
          short-length: 7
      - name: Publish
        env:
          GITHUB_REPO_REF: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_BRANCH: ${{ env.GITHUB_REF_SLUG_URL }}

          RELEASE: 'false'

          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: nix develop .#ci -c sdks/dotnet/scripts/ci/publish.sh

  release:
    name: Semantic Release
    needs:
      - precommit
      - publishdotnet
      - publishnode
    if: github.ref == 'refs/heads/main'
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-sulfone-helium-release-cache
      - nscloud-git-mirror-1gb
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v1.2.1
      - uses: AtomiCloud/actions.cache-nuget@v1.0.1

        # Publish
      - uses: rlespinasse/github-slug-action@v5.x
        with:
          short-length: 7

      - name: Release
        env:
          GITHUB_REPO_REF: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_BRANCH: ${{ env.GITHUB_REF_SLUG_URL }}

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: nix develop .#releaser -c scripts/ci/release.sh

      - name: Publish
        env:
          GITHUB_REPO_REF: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_BRANCH: ${{ env.GITHUB_REF_SLUG_URL }}

          RELEASE: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          NPM_API_KEY: ${{ secrets.NPM_API_KEY }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: nix develop .#ci -c scripts/ci/publish.sh
