name: CD

on:
  workflow_call:
    inputs:
      atomi_platform:
        required: true
        type: string
      atomi_service:
        required: true
        type: string

jobs:
  publish:
    name: Publish NuGet Package
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-${{ inputs.atomi_platform }}-${{ inputs.atomi_service }}-nix-store-cache
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v2
      - uses: AtomiCloud/actions.cache-npm@v1
      - uses: AtomiCloud/actions.cache-nuget@v1
      # TODO: Add cache for pypi

      # Build and Publish
      - name: Build and Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NPM_API_KEY: ${{ secrets.NPM_API_KEY }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: nix develop .#ci -c ./scripts/publish.sh
